# Association Rules

In [17]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [18]:
df = pd.read_excel("Online retail.xlsx", header=None)
df.head()

                                                   0
0  shrimp,almonds,avocado,vegetables mix,green gr...
1                             burgers,meatballs,eggs
2                                            chutney
3                                     turkey,avocado
4  mineral water,milk,energy bar,whole wheat rice...

In [19]:
#Data Preprocessing
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

In [20]:
transactions = []
for row in df[0]:
    items = row.split(",")
    items = [item.strip() for item in items]
    transactions.append(items)

print("Total Transactions:", len(transactions))

Total Transactions: 5176

In [21]:
# One-Hot Encoding
te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)
basket = pd.DataFrame(te_data, columns=te.columns_)
basket.head()

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,True,True,False,True,False,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [22]:
#Applying Apriori
frequent_items = apriori(basket,min_support=0.03,use_colnames=True)
frequent_items.sort_values(by="support", ascending=False).head(10)

     support                        itemsets
32  0.299845      frozenset({mineral water})
41  0.229521          frozenset({spaghetti})
12  0.208076               frozenset({eggs})
8   0.205178          frozenset({chocolate})
16  0.192620       frozenset({french fries})
31  0.170015               frozenset({milk})
23  0.169243          frozenset({green tea})
24  0.135819        frozenset({ground beef})
21  0.129830  frozenset({frozen vegetables})
35  0.125193           frozenset({pancakes})

In [23]:
#Generating Association Rules
rules = association_rules(frequent_items,metric="confidence",min_threshold=0.3) #Atleast 30% confidence
rules = rules.sort_values(by="lift",ascending=False)
rules[['antecedents','consequents','support','confidence','lift']].head(20)

,antecedents,consequents,support,confidence,lift
9,frozenset({ground beef}),frozenset({spaghetti}),0.055835,0.411095,1.791102
18,frozenset({olive oil}),frozenset({spaghetti}),0.032457,0.370044,1.612246
15,frozenset({soup}),frozenset({mineral water}),0.033423,0.471390,1.572109
0,frozenset({burgers}),frozenset({eggs}),0.036128,0.317487,1.525826
12,frozenset({olive oil}),frozenset({mineral water}),0.038640,0.440529,1.469186
8,frozenset({ground beef}),frozenset({mineral water}),0.058733,0.432432,1.442184
19,frozenset({shrimp}),frozenset({spaghetti}),0.030332,0.306641,1.336003
11,frozenset({milk}),frozenset({mineral water}),0.067813,0.398864,1.330231
7,frozenset({frozen vegetables}),frozenset({spaghetti}),0.039026,0.300595,1.309664
3,frozenset({chicken}),frozenset({mineral water}),0.032651,0.389401,1.298672
13,frozenset({pancakes}),frozenset({mineral water}),0.048686,0.388889,1.296964
6,frozenset({frozen vegetables}),frozenset({mineral water}),0.050425,0.388393,1.295310
17,frozenset({tomatoes}),frozenset({mineral water}),0.034583,0.376050,1.254148
16,frozenset({spaghetti}),frozenset({mineral water}),0.085008,0.370370,1.235204
2,frozenset({cake}),frozenset({mineral water}),0.037674,0.363806,1.213312
4,frozenset({chocolate}),frozenset({mineral water}),0.073223,0.356874,1.190193
10,frozenset({low fat yogurt}),frozenset({mineral water}),0.032651,0.343496,1.145577
14,frozenset({shrimp}),frozenset({mineral water}),0.033617,0.339844,1.133396
5,frozenset({eggs}),frozenset({mineral water}),0.070131,0.337047,1.124070
1,frozenset({burgers}),frozenset({mineral water}),0.034583,0.303905,1.013539

In [24]:
print("Total Rules:", len(rules))
print("\nTop Frequent Itemsets")
print(frequent_items.sort_values(by="support", ascending=False).head(10))

print("\nTop Association Rules")
print(rules[['antecedents','consequents','support','confidence','lift']].head(10))

Total Rules: 20

Top Frequent Itemsets
     support                        itemsets
32  0.299845      frozenset({mineral water})
41  0.229521          frozenset({spaghetti})
12  0.208076               frozenset({eggs})
8   0.205178          frozenset({chocolate})
16  0.192620       frozenset({french fries})
31  0.170015               frozenset({milk})
23  0.169243          frozenset({green tea})
24  0.135819        frozenset({ground beef})
21  0.129830  frozenset({frozen vegetables})
35  0.125193           frozenset({pancakes})

Top Association Rules
                       antecedents                 consequents   support  \
9         frozenset({ground beef})      frozenset({spaghetti})  0.055835
18          frozenset({olive oil})      frozenset({spaghetti})  0.032457
15               frozenset({soup})  frozenset({mineral water})  0.033423
0             frozenset({burgers})           frozenset({eggs})  0.036128
12          frozenset({olive oil})  frozenset({mineral water})  0.038640
8         frozenset({ground beef})  frozenset({mineral water})  0.058733
19             frozenset({shrimp})      frozenset({spaghetti})  0.030332
11               frozenset({milk})  frozenset({mineral water})  0.067813
7   frozenset({frozen vegetables})      frozenset({spaghetti})  0.039026
3             frozenset({chicken})  frozenset({mineral water})  0.032651

    confidence      lift
9     0.411095  1.791102
18    0.370044  1.612246
15    0.471390  1.572109
0     0.317487  1.525826
12    0.440529  1.469186
8     0.432432  1.442184
19    0.306641  1.336003
11    0.398864  1.330231
7     0.300595  1.309664
3     0.389401  1.298672

### Observations

* High support means items appear frequently.
* High confidence means the rule is reliable.
* Lift greater than 1 indicates a positive association.
* These rules help businesses recommend products and improve sales.

### Interview Questions

(Q) What is Lift and why is it important in Association Rules?

* Lift measures how strongly two items are associated compared to if they were independent.
* Lift(A->B) = Confidence(A->B)/Support(B)
* Lift > 1: Positive association between items. Lift = 1: No association. Lift < 1: Negative association.

(Q) What are Support and Confidence? How do you calculate them?
* Support measures how frequently an itemset appears in the dataset.
* Support(A->B) = (Transactions containing both A & B) / Total Transactions
* Confidence measures how often item B appears when item A is present.
* Confidence(A->B) = (Support A union B) / Support(A)

(Q) What are some limitations or challenges of Association Rule Mining?
* It can generate a very large number of rules, making analysis difficult.
* Choosing appropriate minimum support and confidence values can be challenging.
* It requires high computational time for large datasets.